### ISSUE TITLE
Use an api instead of icons for **icons**

### ISSUE THREAD

**Issue by ThorinDev** [Chatout/chatout.github.io#33]
https://minotar.net/avatar/clone1018/160 <- for instance

**Comment by ThorinDev** [comment]
Anyway I think I closed this in my last commit 15da340

**Comment by Eladkay** [comment]
Can you look into Gravatar, I think it's called?

**Comment by ThorinDev** [comment]
@Eladkay can you come on slack?

**Comment by ThorinDev** [comment]
Going to leave this closed for now, but if I find try and contact me when you are back.
