### ISSUE TITLE
when email input is null, servers return an error.

### ISSUE THREAD

**Issue by Eladkay** [Chatout/chatout.github.io#45]

**Comment by ThorinDev** [comment]
This is actually a feature. Or would you like me to write a special case for this?

**Comment by ThorinDev** [comment]
Just gonna leave this closed. Makes no sense

**Comment by Eladkay** [comment]
Yes. Users should be notified that they need to actually type an email, and not be told the problem is in our side.

**Comment by ThorinDev** [comment]
Ok that is pretty easy to do

**Comment by Eladkay** [comment]
Closed cd3dbf1
